예제 7.6 ~ 7.10 자연어 전처리

In [ ]:
# 예제 7.6(a) NLTK(Natural Language Tool Kit) 토큰화

import nltk
nltk.download('punkt')   # 토크나이저 다운로드
from nltk.tokenize import word_tokenize, sent_tokenize

sentences = "I like reading very much. I also like movies."

tokens = word_tokenize(sentences)            # 단어 토큰화
sentence_tokens = sent_tokenize(sentences)   # 문장 토큰화

print(tokens)
print(sentence_tokens)

['I', 'like', 'reading', 'very', 'much', '.', 'I', 'also', 'like', 'movies', '.']
['I like reading very much.', 'I also like movies.']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
# 예제 7.6(b) 한글 형태소 분석

!pip install konlpy
from konlpy.tag import Okt

sentence = "나는 독서를 좋아한다."

okt=Okt()

print(okt.morphs(sentence))   # 형태소 분석(토큰)
print(okt.pos(sentence))      # 형태소 분석/품사(Part of Speech)
print(okt.nouns(sentence))    # 명사 추출

['나', '는', '독서', '를', '좋아한다', '.']
[('나', 'Noun'), ('는', 'Josa'), ('독서', 'Noun'), ('를', 'Josa'), ('좋아한다', 'Adjective'), ('.', 'Punctuation')]
['나', '독서']


In [ ]:
# 예제 7.6(c) 불용어 제거(NLTK 불용어

import nltk
nltk.download('stopwords')   # 불용어 다운로드
from nltk.corpus import stopwords

sentence = "I like reading very much."
sentence = sentence.lower().replace(".", " ")   # 소문자로 대체/구두점 제거

stop_words = stopwords.words('english')   # 영어 불용어
tokens = word_tokenize(sentence)
tokens_skip = [word for word in tokens if word not in stop_words]

print(len(stop_words))   # 불용어 수 확인
print(stop_words)        # 불용어 확인
print(tokens)            # 토큰화 확인
print(tokens_skip)       # 불용어 처리 후 토큰 확인

179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
# 예제 7.7 텍스트 벡터화

import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

sentences = ["나는 독서를 매우 좋아한다.",
             "나는 영화를 매우 매우 좋아한다."]

vectorizer = TextVectorization()
vectorizer.adapt(sentences)   # 어휘 사전 생성

vocabulary = dict(zip(vectorizer.get_vocabulary(),
                      range(len(vectorizer.get_vocabulary()))))

text_vector = vectorizer(sentences).numpy()   # 텍스트 벡터화

print(f"vocabulary: {vocabulary}")              # 어휘 사전 인덱싱 확인
print(f"text_vectorization:\n {text_vector}")   # 벡터화 확인

vocabulary: {'': 0, '[UNK]': 1, '매우': 2, '좋아한다': 3, '나는': 4, '영화를': 5, '독서를': 6}
text_vectorization:
 [[4 6 2 3 0]
 [4 5 2 2 3]]


In [ ]:
# 예제 7.7 텍스트 벡터화(OOV)

sentence = ['나는 운동도 아주 좋아한다']   # 어휘 사전에 없는 단어를 포함한 문장

text_oov_vector = vectorizer(sentence).numpy()

print(f"text_oov_vectorization: {text_oov_vector}")   # OOV(UNK) 벡터화 확인

text_oov_vectorization: [[4 1 1 3]]


In [ ]:
# 예제 7.8 단어 임베딩(Word2Vec)

!pip install gensim

from gensim.models import Word2Vec

sentences = [["I", "like", "reading", "very", "much"],
             ["I", "also", "like", "movies"]]

model = Word2Vec(sentences,
                 min_count=1,     # 최소 등장 횟수
                 vector_size=2,   # 임베딩 차원
                 window=2,        # 윈도우 크기
                 sg=0)            # CBOW(0)/skip-gram(1)

embedding_vector = model.wv['reading']            # 임베딩 벡터 가져옴
similarity = model.wv.similarity('reading', 'like')   # 단어 간 유사도

print(embedding_vector.round(2))   # 단어 임베딩 벡터 확인
print(similarity.round(2))         # 단어 간 유사도 확인

[-0.23  0.33]
0.85


In [ ]:
# 예제 7.9 임베딩(텐서플로)

import tensorflow as tf
from tensorflow.keras.layers import Embedding
import numpy as np

vocab_size = 10     # 어휘 사전 크기
embedding_dim = 3   # 임베딩 차원

embedding = Embedding(input_dim=vocab_size, output_dim=embedding_dim)

inputs = tf.constant([3, 5])   # 단어 정수값
embedding_vector = embedding(inputs)

print(np.round(embedding_vector, 4))

[[ 0.0175  0.0362  0.0238]
 [-0.016  -0.0131  0.0106]]


In [ ]:
# 예제 7.9 임베딩(파이토치)

import torch
import torch.nn as nn

vocab_size = 10     # 어휘 사전 크기
embedding_dim = 3   # 임베딩 차원

embedding = nn.Embedding(num_embeddings=vocab_size,
                         embedding_dim=embedding_dim)

inputs = torch.LongTensor([3, 5])  # 단어 인덱스 값(정수)
embedding_vector = embedding(inputs)

print(embedding_vector)

tensor([[ 0.0204,  0.9657, -0.0306],
        [-0.2895,  2.2462,  0.0656]], grad_fn=<EmbeddingBackward0>)


In [ ]:
# 예제 7.10 Embedding 계층 파라미터 수

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

vocab_size = 10000    # 어휘 사전 크기
embedding_dim = 128   # 임베딩 차원

model = Sequential(name='Embedding')
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim))
model.add(LSTM(16))
model.add(Dense(1))

model.summary()

Model: "Embedding"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 128)         1280000   
                                                                 
 lstm (LSTM)                 (None, 16)                9280      
                                                                 
 dense (Dense)               (None, 1)                 17        
                                                                 
Total params: 1,289,297
Trainable params: 1,289,297
Non-trainable params: 0
_________________________________________________________________
