예제 3.8 선형 회귀(파이토치)

In [ ]:
# 예제 3.8 선형 회귀(파이토치)

# 셋업
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
import numpy as np

In [ ]:
# 데이터 준비
x_train = init.uniform_(torch.Tensor(200, 1), 0, 10)
y_train = (2 * x_train + 1) + init.normal_(torch.FloatTensor(200, 1))

print(x_train.shape, y_train.shape)

torch.Size([200, 1]) torch.Size([200, 1])


In [ ]:
# 모델 생성
model = nn.Sequential(
    nn.Linear(1, 1))   # 입력 특징 1개, 출력 뉴런 1개

In [ ]:
# 모델 학습
epochs = 100

loss_fn = nn.L1Loss()   # 손실 함수 MAE 사용
optimizer = optim.Adam(model.parameters(),lr=0.1)

for i in range(epochs):
    output = model(x_train)           # 출력 구함
    loss = loss_fn(output, y_train)   # 오차 계산

    optimizer.zero_grad()   # 그레디언트 초기화
    loss.backward()         # 역전파
    optimizer.step()        # 최적화 수행

    if (i+1) % 10 == 0:
       print(f"epoch: {i + 1} \tloss: {loss}")

epoch: 10 	loss: 4.980434417724609
epoch: 20 	loss: 1.0660961866378784
epoch: 30 	loss: 1.0262762308120728
epoch: 40 	loss: 1.0040247440338135
epoch: 50 	loss: 0.8527184128761292
epoch: 60 	loss: 0.7826300859451294
epoch: 70 	loss: 0.7567226886749268
epoch: 80 	loss: 0.7454615831375122
epoch: 90 	loss: 0.7395433783531189
epoch: 100 	loss: 0.7383608818054199


In [ ]:
# 모델 예측
with torch.no_grad():   # 자동 미분하지 않음
     x_test = torch.Tensor([[3], [5], [7], [9]])

     predict = model(x_test)

     print(predict)

tensor([[ 6.9165],
        [10.9732],
        [15.0299],
        [19.0866]])


In [ ]:
# 학습 후 최종 가중치 확인
weight, bias = model.parameters()

print(f"weight: {weight} \n \n bias: {bias}")

weight: Parameter containing:
tensor([[2.0284]], requires_grad=True) 
 
 bias: Parameter containing:
tensor([0.8314], requires_grad=True)
