예제 4.3 다층 신경망 분류기(XOR)

In [ ]:
# 예제 4.3 다층 신경망 분류기(XOR 연산)

# 셋업
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import RandomNormal
import numpy as np

# 데이터 준비
x_train = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])   # 학습 데이터
y_train = np.array([[0], [1], [1], [0]])               # 레이블(정답)

# 모델 생성
model = Sequential([
    Dense(2, activation='sigmoid',                   # 은닉층 뉴런 2개
          kernel_initializer=RandomNormal(seed=7),   # 가중치 초기화
          input_shape=(2, ), name='Hidden_Layer'),
    Dense(1,                                         # 출력층 뉴런 1개
          kernel_initializer=RandomNormal(seed=7),
          activation='sigmoid',                      # sigmoid 함수 사용
          name='Output_Layer')
])

In [ ]:
# 은닉층의 초기 가중치와 바이어스 확인
model.layers[0].weights

[<tf.Variable 'Hidden_Layer/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.00234728, -0.06019512],
        [ 0.05834176,  0.05853102]], dtype=float32)>,
 <tf.Variable 'Hidden_Layer/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [ ]:
# 출력층의 초기 가중치와 바이어스 확인
model.layers[1].weights

[<tf.Variable 'Output_Layer/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-0.01112203],
        [ 0.07618172]], dtype=float32)>,
 <tf.Variable 'Output_Layer/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [ ]:
# 모델 컴파일
model.compile(loss='mean_squared_error', optimizer='adam')

In [ ]:
# 모델 학습
model.fit(x_train, y_train, epochs=10000, verbose=0)

In [ ]:
# 모델 예측
x_test = np.array([[0, 0],[0, 1], [1, 0], [1, 1]])   # 테스트 데이터
y_test = np.array([[0], [1], [1], [0]])              # 테스트 정답

model.predict(x_test).round(2)

1/1 [==============================] - 0s 61ms/step


array([[0.03],
       [0.97],
       [0.97],
       [0.03]], dtype=float32)

In [ ]:
# 학습 후 은닉층 가중치와 바이어스 확인
weights, biases = model.layers[0].get_weights()

print(f"weights: {weights.round(1)} \n bias: {biases.round(1)}")

weights: [[-6.8 -6.7]
 [ 6.7  6.7]] 
 bias: [ 3.7 -3.7]


In [ ]:
# 학습 후 출력층 가중치와 바이어스 확인
weights, bias = model.layers[1].get_weights()

print(f"weights: {weights.round(1)} \n bias: {bias.round(1)}")

weights: [[-7.4]
 [ 7.4]] 
 bias: [3.7]
